### ISSUE TITLE
Allow for early termination of the visitor

### ISSUE THREAD

**Issue by LukasPietzschmann** [flowr-analysis/flowr-r-adapter#18]
When visiting nodes in the AST, it could be handy if the visitor would allow for an early exit. This could work as follows:
```r
visit_nodes(ast, function(node) {
  if(some check) {
    # We got what we want, so we do not have to visit more nodes
    return(FALSE)
  }
  # return nothing (or TRUE) to visit more nodes
})
```

If you (@Ellpeck and @EagleoutIce) are fine with this small addition, I already have the code ready :)

**Comment by EagleoutIce** [comment]
This mirrors flowR's behavior of allowing for an early exist, so please go ahead and open the PR :)

**Comment by LukasPietzschmann** [comment]
Maybe one small reiteration: I'm unsure of the _right_ behavior when calling `visit_nodes` with a list of nodes. Should we instantly stop when the callback returns `FALSE` for a single node, or should we continue with the next node in the list?

**Comment by EagleoutIce** [comment]
I think the "intuitive" thing would be to stop early. We define a sequential traversal order through the vector of nodes passed. 
The R-Thing to do would be probably to return a vector greedly containing `TRUE`/`FALSE` for each node individually (i.e., vectorizing over the visitation order). But i think an early exit works perfectly fine.
