### ISSUE TITLE
CI: devtools checks are repeated for push and pull request triggers

### ISSUE THREAD

**Issue by EagleoutIce** [flowr-analysis/flowr-r-adapter#24]
This causes unnecessary re-runs. We should only run them once when someone pushes to a PR (e.g., by removing the push trigger if not on main?)

@LukasPietzschmann and @Ellpeck. What do you think?

**Comment by LukasPietzschmann** [comment]
Sounds reasonable to me

**Comment by EagleoutIce** [comment]
Any of you want to do that? Otherwise I can do it later :)

**Comment by LukasPietzschmann** [comment]
Sure, I'll do it quickly
